# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 16
        architecture: x64
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Build with Maven and deploy to GitHub Packages
      run: mvn -B clean deploy --file pom.xml -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload target
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: MinecraftDecompiler
        path: MinecraftDecompiler.jar
