name: Java CI with Maven

on:
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - CODE_OF_CONDUCT.md
      - src/main/resources
      - src/test/resources
      - decompiler

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up JDK
      uses: actions/setup-java@v2.5.0
      with:
        java-version: 17.0.1
        distribution: temurin
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B clean package
    - name: Upload target
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: MinecraftDecompiler
        path: MinecraftDecompiler.jar
    - name: Deploy to GitHub Packages
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}