name: Java CI with Maven

on:
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - CODE_OF_CONDUCT.md
      - src/main/resources/**
      - src/test/resources/**
      - decompiler/**
      - .github/**
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'MaxPixelStudios/MinecraftDecompiler'
    permissions:
      packages: write
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        check-latest: true
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B clean package
    - name: Upload target
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: MinecraftDecompiler
        path: MinecraftDecompiler.jar
    - name: Deploy to GitHub Packages
      if: success()
      run: |
        mvn -B deploy
        echo "MVN_PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.3.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ github.token }}
#    - name: Pre-release
#      if: ${{ success() && !startsWith(github.event.head_commit.head_commit.message, 'Bump version to ') && !endsWith(github.event.head_commit.head_commit.message, ' Release') }}
#      uses: softprops/action-gh-release@v1
#      with:
#        name: MinecraftDecompiler v${{ env.MVN_PROJECT_VERSION }}+${{ github.sha }} Pre-released
#        tag_name: v${{ env.MVN_PROJECT_VERSION }}+${{ github.sha }}
#        target_commitish: ${{ github.sha }}
#        body: ${{ github.event.head_commit.head_commit.message }}
#        files: MinecraftDecompiler.jar
#        prerelease: true