name: PR Check

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 17.0.1
          distribution: temurin
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B clean package